### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [oxedom/parker#5]
I see you have no LICENSE file for this project. The default is copyright.

I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by oxedom** [comment]
I've added MIT, is that sufficient for this project?

**Comment by TechnologyClassroom** [comment]
MIT is better than copyright with all rights reserved. I believe copyleft is better than permissive licenses because many times others do not contribute to upstream projects when the license does not require. It is ultimately your choice though.
